version: '3.8'

services:
  backend:
    build: ./api
    ports:
      - "5000:5000"

  frontend:
    build: ./ui
    ports:
      - "80:80"

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
