apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deploy
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress-container
        image: wordpress:latest
        env:
          - name: WORDPRESS_DB_HOST
            value: mysql-service      # Matches your MySQL Service name
          - name: WORDPRESS_DB_USER
            value: wpuser
          - name: WORDPRESS_DB_PASSWORD
            value: wppass
          - name: WORDPRESS_DB_NAME
            value: wordpress
        ports:
          - containerPort: 80
        volumeMounts:
          - name: wp-storage
            mountPath: /var/www/html
      volumes:
        - name: wp-storage
          persistentVolumeClaim:
            claimName: wp-pvc
