apiVersion: v1
kind: Pod
metadata:
  name: pvc-example
spec:
  containers:
  - name: my-container
    image: busybox
    command: ['sh', '-c', 'ls /mnt/data && sleep 3600']
    volumeMounts:
    - mountPath: /mnt/data
      name: pvc-storage
  volumes:
  - name: pvc-storage
    persistentVolumeClaim:
      claimName: pvc-example